### PR TITLE
Unify error handling for non-registered remote messages sent via send & notify

### PR DESCRIPTION
**Pull request by RedKinda**
Currently, when I forget to register a handler (`.with_handler::<A, M>` at config time), and then subsequently try to send that message to a remote actor, the notify/send receives an ActorUnavailable error, which is kind of confusing. This PR adds a runtime log to help fix that pretty easy-to-do mistake.

Maybe it would be a good idea to also refactor error handling around create_request, currently it returns an Option with None for all failures

### CODE REVIEW

**Comment by LeonHartley** [comment]
Hey @RedKinda!

I'm with you on the fact that the handling around `create_request` needs a good refactor.

For this PR, I'm not sure if this is the correct place for that log. There's already an error log in place when messages that aren't registered are sent via `RemoteActorRef::send`, there's just nothing there for `RemoteActorRef::notify`.

Would it be better to add correct error propagation inside there, similar to how `send` returns the correct error result, that way we don't get 2 logs when `send` is called on a message that isn't registered?

**Comment by RedKinda** [comment]
Ah yep I didn't notice it in `send` lol. Maybe it would be better to move the warning from `send` to `create_request` to avoid code duplication? It could also return a Result instead of Option and construct `ActorRefErr::NotSupported` directly

**Comment by LeonHartley** [comment]
> 

Yeah sounds good to me!

**Comment by LeonHartley** [comment]
Thanks a lot @RedKinda - please can you pull the latest into your branch, I've made some changes to the test pipeline so we can run it against PRs.

**Pull request merged**
